"""
Convert MPPSC Question Bank to PDF using reportlab
"""

try:
    from reportlab.lib.pagesizes import letter, A4
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib.enums import TA_CENTER, TA_LEFT
    import csv
    import os
    
    print("Creating PDF using reportlab...")
    
    # Define file paths (adjusted for minimal_app)
    base_dir = os.path.dirname(__file__)
    csv_file = os.path.join(base_dir, "mppsc_comprehensive_question_bank.csv")
    sample_file = os.path.join(base_dir, "mppsc_sample_question_paper.txt")
    pdf_file = os.path.join(base_dir, "MPPSC_Question_Bank_and_Sample_Paper.pdf")
    
    # Create PDF document
    doc = SimpleDocTemplate(pdf_file, pagesize=A4, 
                           rightMargin=72, leftMargin=72, 
                           topMargin=72, bottomMargin=18)
    
    # Get styles
    styles = getSampleStyleSheet()
    
    # Create custom styles
    title_style = ParagraphStyle('CustomTitle', 
                                parent=styles['Heading1'],
                                fontSize=18,
                                spaceAfter=30,
                                alignment=TA_CENTER)
    
    section_style = ParagraphStyle('CustomSection',
                                  parent=styles['Heading2'], 
                                  fontSize=14,
                                  spaceAfter=12,
                                  spaceBefore=24)
    
    question_style = ParagraphStyle('CustomQuestion',
                                   parent=styles['Normal'],
                                   fontSize=11,
                                   spaceAfter=12,
                                   leftIndent=20)
    
    # Story list to hold content
    story = []
    
    # Add title
    story.append(Paragraph("MPPSC Comprehensive Question Bank", title_style))
    story.append(Paragraph("Madhya Pradesh Public Service Commission", styles['Heading3']))
    story.append(Spacer(1, 12))
    story.append(Paragraph("Generated by minimal_app", styles['Normal']))
    story.append(Spacer(1, 24))
    
    # Read CSV and organize by subject
    questions_by_subject = {}
    
    if os.path.exists(csv_file):
        with open(csv_file, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                subject = row['subject']
                if subject not in questions_by_subject:
                    questions_by_subject[subject] = []
                questions_by_subject[subject].append(row)
    
    # Add questions by subject
    for subject, questions in questions_by_subject.items():
        # Add section header
        subject_title = subject.replace('_', ' ').title()
        story.append(Paragraph(subject_title, section_style))
        
        for q in questions:
            question_text = f"Q{q.get('id', '')}. {q['question']}"
            
            # Clean up the question text
            question_text = question_text.replace('\n', '<br/>')
            
            story.append(Paragraph(question_text, question_style))
            
            # Add metadata
            meta_text = f"Topic: {q.get('topic','')} | Type: {q.get('type','')} | Difficulty: {q.get('difficulty','')}"
            story.append(Paragraph(f"<i>{meta_text}</i>", styles['Normal']))
            story.append(Spacer(1, 6))
    
    # Add sample paper
    story.append(PageBreak())
    story.append(Paragraph("MPPSC Practice Question Paper", title_style))
    
    if os.path.exists(sample_file):
        with open(sample_file, 'r', encoding='utf-8') as f:
            sample_content = f.read()
            
        # Split into paragraphs and add to story
        paragraphs = sample_content.split('\n\n')
        for para in paragraphs:
            if para.strip():
                # Check if it's a section header
                if para.startswith('Section'):
                    story.append(Paragraph(para, section_style))
                elif para.startswith('MPPSC') or para.startswith('Subject:') or para.startswith('Time:'):
                    story.append(Paragraph(para, styles['Heading3']))
                else:
                    story.append(Paragraph(para.replace('\n', '<br/>'), styles['Normal']))
                story.append(Spacer(1, 6))
    
    # Build PDF
    doc.build(story)
    print(f"PDF successfully created: {pdf_file}")
    
except ImportError:
    print("reportlab is not installed. Please install it via requirements.txt")
except Exception as e:
    print(f"Error creating PDF: {e}")
